pentaho/modeler

src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasure.java

@kurtwalker Please merge.. thx

[BACKLOG-1619] Fix bug where measure name was not getting set

---

src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java
test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationTypeTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/ModelPropertyTest.java

@kurtwalker @pamval - please review

[BACKLOG-1807] Time Format values in Dropdown should depend on Time Type

---

src/org/pentaho/agilebi/modeler/res/analysisModel.xul
src/org/pentaho/agilebi/modeler/res/biserverconfig.xul
src/org/pentaho/agilebi/modeler/res/columnResolver.xul
src/org/pentaho/agilebi/modeler/res/cubeForms.xul
src/org/pentaho/agilebi/modeler/res/measuresForm.xul
src/org/pentaho/agilebi/modeler/res/panel.xul
src/org/pentaho/agilebi/modeler/res/publish.xul
src/org/pentaho/agilebi/modeler/res/reportingForms.xul
src/org/pentaho/agilebi/modeler/res/reportingModel.xul
test-src/org/pentaho/agilebi/modeler/debug/panel_overlay.xul

@pamval, @bytekast would you mind to review/merge?

[PDI-11775] Kettle .xul files contains links to local filesystem

---

src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java

Moving changes from 'develop' branch to 'future-develop' branch

BACKLOG-1768 - Inline modeling prototype - Fix for mondrian data sources

---

src/org/pentaho/agilebi/modeler/messages/messages_en_US.properties
src/org/pentaho/agilebi/modeler/models/annotations/AnnotationType.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateDimensionKey.java
src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java
src/org/pentaho/agilebi/modeler/models/annotations/ModelProperty.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateDimensionKeyTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationMetastoreTest.java

@bytekast @kurtwalker @pamval please review

[BACKLOG-2344] CreateDimensionKey annotation type

---

test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationMetastoreTest.java

@kurtwalker @tgf @pamval - please review

[BACKLOG-2710] Test MetaStore Save/Load for LinkDimension Annotation

---

build.properties
ivy.xml
src/org/pentaho/agilebi/modeler/messages/messages_en_US.properties
src/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMember.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasure.java
src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java
src/org/pentaho/agilebi/modeler/models/annotations/RemoveMeasure.java
src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMemberTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandlerTest.java

Added annotation support for adding calculated members to analysis data sources and removing measures

Inline modeling calc measure working remove measure merge

---

src/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMember.java
src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java
src/org/pentaho/agilebi/modeler/models/annotations/RemoveMeasure.java

Updated overriden methods because of changed method signatures

Fixing some additional master merge issues

---

src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationManager.java

@bytekast @pamval please review

[BACKLOG-3007] db meta save; also ensure namespaces before

---

src/org/pentaho/agilebi/modeler/models/annotations/CreateAttribute.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeTest.java

@bytekast @kurtwalker @pamval please review

[BACKLOG-3090] time dim not set when dim name same as field

---

src/org/pentaho/agilebi/modeler/BaseModelerWorkspaceHelper.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateAttribute.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasure.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasureTest.java

@bytekast @kurtwalker @pamval please review

[BACKLOG-3146] descriptions in analyzer

---

src/org/pentaho/agilebi/modeler/BaseModelerWorkspaceHelper.java

[BACKLOG-3146] avoid stringUtils for data-access gwt

---

src/org/pentaho/agilebi/modeler/nodes/HierarchyMetaData.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeTest.java

@bytekast @kurtwalker @pamval please review

[BACKLOG-3219] stack overflow on validation loop

---

src/org/pentaho/agilebi/modeler/messages/messages_en_US.properties
src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java
src/org/pentaho/agilebi/modeler/models/annotations/RemoveAttribute.java
test-src/org/pentaho/agilebi/modeler/models/annotations/RemoveAttributeTest.java

@bennychow @dcleao @pminutillo @bytekast @kurtwalker Any comments would be appreciated. Thank you!

Added remove attribute annotation

---

src/org/pentaho/agilebi/modeler/models/annotations/LinkDimension.java
test-src/org/pentaho/agilebi/modeler/models/annotations/LinkDimensionTest.java

@bytekast @pamval please review

[BACKLOG-3033] Link Dimension was removing its own dimension

---

src/org/pentaho/agilebi/modeler/messages/messages_en_US.properties
src/org/pentaho/agilebi/modeler/models/annotations/AnnotationType.java
src/org/pentaho/agilebi/modeler/models/annotations/BlankAnnotation.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateAttribute.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMember.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateDimensionKey.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasure.java
src/org/pentaho/agilebi/modeler/models/annotations/LinkDimension.java
src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java
src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroup.java
src/org/pentaho/agilebi/modeler/models/annotations/RemoveAttribute.java
src/org/pentaho/agilebi/modeler/models/annotations/RemoveMeasure.java
test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationTypeTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationUtil.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMemberTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateDimensionKeyTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasureTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/LinkDimensionTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/MockAnnotationType.java
test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroupTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationMetastoreTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/ModelPropertyTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/RemoveAttributeTest.java
test-src/org/pentaho/di/core/refinery/model/ModelAnnotationManagerTest.java

Refactored annotations to accommodate different types of sources (field, level, etc).
@pminutillo @kurtwalker @bytekast @dcleao @bennychow

[BACKLOG-3284] Refactored annotations for field

---

test-src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasureTest.java

@kurtwalker @bytekast  @pminutillo - please review

[CLEANUP] Auto merge fix

---

src/org/pentaho/agilebi/modeler/messages/messages_en_US.properties
src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasure.java
src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java
src/org/pentaho/agilebi/modeler/models/annotations/RemoveAttribute.java
src/org/pentaho/agilebi/modeler/models/annotations/RemoveMeasure.java
src/org/pentaho/agilebi/modeler/models/annotations/UpdateMeasure.java
src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java
test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationUtil.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMemberTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/UpdateMeasureTest.java

@kurtwalker @bytekast @bennychow @pminutillo Please review.

[BACKLOG-1531] Update measure name using annotation

---

src/org/pentaho/agilebi/modeler/models/annotations/RemoveMeasure.java
src/org/pentaho/agilebi/modeler/models/annotations/UpdateMeasure.java
src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java
test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationUtil.java
test-src/org/pentaho/agilebi/modeler/models/annotations/UpdateMeasureTest.java

@bennychow @pminutillo @bytekast @kurtwalker please review

[BACKLOG-1531] Update measure aggregation

---

src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroupXmlReader.java
test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroupXmlReaderTest.java

ModelAnnotationMeta
What was done:
1) code refactored
2) unit tests created

BACKLOG-4274 -- factor out ModelAnnotationGroupReader from

---

build.properties

with the build teams property list.
@lucboudreau

[CLEANUP] Removing unused property that is inconsistent

---

src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java

Step
What was done:
1) changed wording according to UX requirements

BACKLOG-5024 -- Model Action terminology inconsistent in Annotate Stream

---

src/org/pentaho/agilebi/modeler/BaseModelerWorkspaceHelper.java
test-src/org/pentaho/agilebi/modeler/BaseModelerWorkspaceHelperTest.java

- Added checking empty list "existingCubes" to avoid IndexOfBoundsException. This is the reason of hang popup.
- Added unit test to the new scenario.

[BACKLOG-4900] DSW - After editing automated DS Model Editor hangs when closing

---

src/org/pentaho/agilebi/modeler/propforms/GenericPropertiesForm.java

@rfellows @pentaho-nbaker super low priority.  I can't even really explain why this fixes the issue.  I spent most of yesterday looking for any differences in behavior with this change (other than fixing the bug) and found nothing.  You guys were the last ones in here.....4 years ago.  So, ya, review at your leisure.

[BACKLOG-4341] - removing visibility toggeling.

---

src/org/pentaho/agilebi/modeler/nodes/MeasuresCollection.java

tab after trying to delete Measure or Dimension section
What was done:
1) added check if the update should be fired to all the listeners

[BACKLOG-4341] -- Spoon Model Editor - Unable to add fields to Analysis

---

src/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMember.java
src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java
test-src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandlerTest.java

measures in field list
What was done:
1) added inline flag for marking calculated measures created via Analyzer
2) added ability to send custom annotations to UI for opening menu

BACKLOG-5944 -- Add "Properties" context menu option for calculated

---

src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroupXmlReader.java

@rfellows @kurtwalker @kolinus @DFieldFL @bennychow  Please review and merge whenever you have a chance.

[BACKLOG-6228] Fix for saving updated calc member annotation

---

src/org/pentaho/agilebi/modeler/ModelerWorkspace.java
src/org/pentaho/agilebi/modeler/Util.gwt.xml
src/org/pentaho/agilebi/modeler/format/DataFormatHolder.java
src/org/pentaho/agilebi/modeler/gwt/BogoPojo.java
src/org/pentaho/agilebi/modeler/propforms/MeasuresPropertiesForm.java
test-src/org/pentaho/agilebi/modeler/ModelerWorkspaceTest.java

[CLEANUP] Moved DataFormatHolder to a new package

---

src/org/pentaho/agilebi/modeler/models/annotations/AnnotationType.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateAttribute.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMember.java
src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasure.java
src/org/pentaho/agilebi/modeler/models/annotations/LinkDimension.java
src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroup.java
test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationTypeTest.java
test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeTest.java

[BACKLOG-8241] - Adding metadata injection support to the Annotate Stream step

[BACKLOG-8241] - Adding metadata injection support to the Annotate Stream step

---

core/src/test/java/org/pentaho/agilebi/modeler/models/JoinTableModelTest.java

What was done:
additional branch of code covered with test.

CLEANUP-- changing tests to see sonar reaction

---

core/src/it/java/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMemberIT.java
core/src/main/java/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMember.java

[ANALYZER-3430] Calculated measure created using inline modeling feature in Analyzer is saved on a different cube than where it was created

---

core/src/main/java/org/pentaho/agilebi/modeler/models/annotations/util/XMLUtil.java

@kurtwalker, @rfellows, @mbatchelor, could you please take a look?

[PPP-3506] - XXE Security Vulnerability in xml parsers

---

core/src/it/resources/ESAPI.properties
core/src/test/resources/ESAPI.properties

Removing legacy ESAPI encoder from projects and replacing it by org.owasp.encoder

PDI-15515- Removing legacy ESAPI encoder from projects

---

core/src/it/java/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeIT.java
core/src/main/java/org/pentaho/agilebi/modeler/models/annotations/AnnotationType.java

What was done:
1) fixed the issue
2) adde integration test.

BACKLOG-10910 -- Can't annotate the same field twice

---

core/src/main/java/org/pentaho/agilebi/modeler/models/annotations/AnnotationType.java
core/src/test/resources/products.mondrian.xml

related to Pull Request https://github.com/pentaho/modeler/pull/314 . Wingman will hopefully give us a green for styling.

[CLEANUP] removed trailing spaces and fix upstream changes for xml

---

pom.xml

TO BE MERGED BY BUILDTEAM ONLY!   Pending upstream mavenization of reporting.

[BACKLOG-12334] GAV changes for reporting

---

core/src/main/java/org/pentaho/agilebi/modeler/ColResolverController.java
core/src/main/java/org/pentaho/agilebi/modeler/geo/GeoContextFactory.java
core/src/test/java/org/pentaho/agilebi/modeler/models/annotations/ModelingSchemaAnnotatorTest.java

* Fix for the issue & small refactoring
* Fix for test not related to the issue: ModelingSchemaAnnotatorTest

[ANALYZER-2745]-latitude and longitude attributes not being set properly when editing a data model

---

.gitignore
README.md

@pentaho/2-1b @pminutillo Please Review

[BACKLOG-15557] Adding README.md file

---

core/pom.xml
pom.xml

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-1757] version name consolidation

---

core/pom.xml
pom.xml

Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/649

[BACKLOG-20163] Update downstreams

---

pom.xml

[CLEANUP] Cleaning duplicate declarations

---

architecture.txt
core/pom.xml
pom.xml

@pentaho/2-1b 
Depends on pentaho/pentaho-commons-xul#143

[BACKLOG-20423] Update downstreams

---

pom.xml

@lgrill-pentaho @emartin-pentaho

[BACKLOG-22034] remove unused commons-database prop

---

core/src/main/java/org/pentaho/agilebi/modeler/ModelerWorkspace.java

Fixes setting the default mask for NUMERIC to #

[PIR-1440] PIR - Prompt - Query Editor Preview shows null+number for numeric fields.

---

pom.xml

[BACKLOG-37368] Update bouncycastle dependencies to match license

---

pom.xml

projects.
This commit is a cherry-pick from master 91b75b2

[BACKLOG-37531] Update BC dependencies to be consistent across all

---

core/src/main/java/org/pentaho/agilebi/modeler/nodes/AvailableField.java
core/src/main/java/org/pentaho/agilebi/modeler/nodes/BaseColumnBackedMetaData.java
core/src/main/java/org/pentaho/agilebi/modeler/nodes/CategoryMetaData.java
core/src/main/java/org/pentaho/agilebi/modeler/nodes/CategoryMetaDataCollection.java
core/src/main/java/org/pentaho/agilebi/modeler/nodes/DimensionMetaData.java
core/src/main/java/org/pentaho/agilebi/modeler/nodes/DimensionMetaDataCollection.java
core/src/main/java/org/pentaho/agilebi/modeler/nodes/HierarchyMetaData.java
core/src/main/java/org/pentaho/agilebi/modeler/nodes/MeasuresCollection.java

@pentaho/millenniumfalcon @pentaho/wcag please review

[BACKLOG-36864] Page Zoom (AA) - Make Datasource Model Editor dialog table's icons zoomable

---

core/pom.xml
gwt/pom.xml
pom.xml

[CLEANUP] updated versions via release version merger

Merging master into wcag

---

pom.xml

[PPP-4747] -Vulnerable Component :batik-1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4747] -Vulnerable Component :batik-1.19

---

core/pom.xml
core/src/it/java/org/pentaho/agilebi/modeler/geo/GeoContextIT.java
core/src/it/java/org/pentaho/di/core/refinery/model/ModelAnnotationManagerIT.java
pom.xml

Use Mockito instead of EasyMock
@pentaho/tatooine_dev

[BACKLOG-43746] Fix Integration Tests errors
